[package]
name = "ffi_leetcode"
version = "0.1.0"
edition = "2021"

[lib]
name = "ffi_leetcode"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"

